version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app  # Montage explicite du répertoire app
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - LLM_URL=http://llm:8001
      - VECTOR_DB_URL=http://vector_db:6333
      - API_PREFIX=/api/v1
    command: >
      sh -c "
        echo 'Debug: Files in container:' && 
        ls -la && 
        python -m uvicorn main:app --host 0.0.0.0 --port 8000
      " 