version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: docker-backend-1
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_PREFIX=/api/v1
      - LLM_URL=http://llm:8001
      - VECTOR_DB_URL=http://vector_db:6333
    volumes:
      - ../backend:/app
      - ../data:/app/data
    depends_on:
      - llm
      - vector_db

  llm:
    build:
      context: ..
      dockerfile: docker/Dockerfile.llm
    container_name: docker-llm-1
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MODEL_NAME=distilbert/distilbert-base-uncased
      - USE_MODEL=false
      - USE_OPENAI=false
    volumes:
      - ../llm:/app
      - ../data:/app/data

  vector_db:
    image: qdrant/qdrant
    container_name: docker-vector_db-1
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../data/vector_db:/qdrant/storage
      - ../vector_db/qdrant_config.json:/qdrant/config/config.json

  chatbot-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    container_name: docker-chatbot-ui-1
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app
    command: >
      bash -c "cd /app && yarn install && yarn dev"
    depends_on:
      - backend

volumes:
  qdrant_data:
    driver: local

